name: template
description: "A new Flutter project."
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.11
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  dio: ^5.5.0+1
  flutter_animate: ^4.5.0
  # todo native splash screen
  flutter_svg: ^2.0.10+1
  provider: ^6.1.2
  logger: ^2.4.0
  go_router: ^14.2.1
  haptic_feedback: ^0.5.1+1
  overlay_support: ^2.1.0
  shared_preferences: ^2.2.3
  skeletonizer: ^1.4.1+1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true